name: App for Bongo Assesment

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install pip dependencies
        run: pip install -r requirements.txt
      - uses: actions/upload-artifact@master
        with:
          name: base
          path: .
  test-build:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@master
        with:
          name: base
          path: .
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install develeopment dependencies
        run: pip install -r requirements-dev.txt
      - uses: actions/upload-artifact@master
        with:
          name: testing
          path: .
  lint:
    runs-on: ubuntu-latest
    needs: [test-build]
    steps:
      - uses: actions/download-artifact@master
        with:
          name: base
          path: .
      - name: Setup dev dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Running mypy
        run: |
          mypy --strict .
  test:
    runs-on: ubuntu-latest
    needs: [test-build]
    steps:
      - name: Setup dev dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - uses: actions/download-artifact@master
        with:
          name: testing
      - name: Testing
        run: |
          cp sample.env .env
          pytest
