name: App for Bongo Assesment

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install pip dependencies
        run: pip install -r requirements.txt
      - name: Testing
        run: |
          cp sample.env .env
          pytest
